"""empty message

Revision ID: 233f9be1e422
Revises: c605ec5cae98
Create Date: 2025-07-11 21:23:38.675577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233f9be1e422'
down_revision = 'c605ec5cae98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_planetas', sa.Integer(), nullable=True))
        batch_op.drop_constraint('planetas_id_usuario_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planetas', ['id_planetas'], ['id'])
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('planetas_id_usuario_fkey', 'usuario', ['id_usuario'], ['id'])
        batch_op.drop_column('id_planetas')

    # ### end Alembic commands ###
