"""empty message

Revision ID: 3af8879c7a46
Revises: 6b70992a8143
Create Date: 2025-07-11 21:15:49.568197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af8879c7a46'
down_revision = '6b70992a8143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardar', schema=None) as batch_op:
        batch_op.drop_constraint('guardar_id_usuario_fkey', type_='foreignkey')
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('guardar_id_usuario_fkey', 'usuario', ['id_usuario'], ['id'])

    # ### end Alembic commands ###
