"""empty message

Revision ID: 403a8157b539
Revises: b785fbe984e4
Create Date: 2025-07-11 21:26:23.364220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403a8157b539'
down_revision = 'b785fbe984e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_personajes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_planetas', sa.Integer(), nullable=False))
        batch_op.drop_column('personajes_id')
        batch_op.drop_column('planetas_id')

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personajes', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['personajes'])
        batch_op.drop_constraint('personajes_personajes_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['id_usuario'], ['id'])
        batch_op.drop_column('personajes_id')

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.Integer(), nullable=True))
        batch_op.drop_constraint('planetas_planetas_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['id_usuario'], ['id'])
        batch_op.drop_column('planetas_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planetas_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('planetas_planetas_id_fkey', 'planetas', ['planetas_id'], ['id'])
        batch_op.drop_column('id_usuario')

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personajes_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('personajes_personajes_id_fkey', 'personajes', ['personajes_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id_usuario')
        batch_op.drop_column('personajes')

    with op.batch_alter_table('guardar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planetas_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('personajes_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('id_planetas')
        batch_op.drop_column('id_personajes')

    # ### end Alembic commands ###
