"""empty message

Revision ID: 6b70992a8143
Revises: be8073fadb22
Create Date: 2025-07-11 21:11:06.754310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b70992a8143'
down_revision = 'be8073fadb22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_personajes', sa.Integer(), nullable=False),
    sa.Column('id_planetas', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_personajes', 'id_planetas')
    )
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personajes', sa.String(length=120), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personajes')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personajes')
    op.drop_table('guardar')
    # ### end Alembic commands ###
