"""empty message

Revision ID: b785fbe984e4
Revises: 233f9be1e422
Create Date: 2025-07-11 21:24:51.746855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b785fbe984e4'
down_revision = '233f9be1e422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personajes_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('planetas_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id_personajes')
        batch_op.drop_column('id_planetas')

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personajes_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('personajes_id_personajes_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'personajes', ['personajes_id'], ['id'])
        batch_op.drop_column('id_personajes')

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planetas_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('planetas_id_planetas_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planetas', ['planetas_id'], ['id'])
        batch_op.drop_column('id_planetas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_planetas', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('planetas_id_planetas_fkey', 'planetas', ['id_planetas'], ['id'])
        batch_op.drop_column('planetas_id')

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_personajes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('personajes_id_personajes_fkey', 'personajes', ['id_personajes'], ['id'])
        batch_op.drop_column('personajes_id')

    with op.batch_alter_table('guardar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_planetas', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_personajes', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('planetas_id')
        batch_op.drop_column('personajes_id')

    # ### end Alembic commands ###
